// App/assets/events/EventsMock.tsx

export const events = [
  //NULL값은 추후 수정 필요할수도?
  {
    id: 1,
    artist: "BTS",
    date: "2025.08.15",
    location: "서울 올림픽 주경기장",
    price: 165000,
    status: "인기",
    image_url: "https://placehold.co/165x160",
    type: "popular",
    name: "BTS 월드투어 2025",
    max_reserve : 4,
    genre : "콘서트",

    reservationNo: "T2025071512345",
    ticket_date: "2025.07.15 (화) 19:00",
    seat_grade: "VIP석",
    seat_number: "L열 14",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    authDate: "2025.07.01 14:23",
  },
  {
    id: 2,
    artist: "심바, 닐라",
    date: "2025.07.20",
    location: "예술의전당",
    price: 120000,
    status: "마감임박",
    image_url: "https://placehold.co/165x160",
    type: "popular",
    name: "라이언 킹",
    max_reserve : 6,
    genre : "뮤지컬",

    reservationNo: "",
    ticket_date: "",
    seat_grade: "",
    seat_number: "",
    ticket_status: "null",
    ticket_statusText: "null",
    primaryButton: "null",
    primaryButtonAction: "null",
    authDate: "",
  },
  {
    id: 3,
    artist: "두산, LG",
    date: "2025.07.25",
    ticket_date: "2025.07.25",
    location: "잠실야구장",
    price: 18000,
    status: "예매중",
    image_url: "https://placehold.co/165x160",
    type: "new",
    name: "두산 VS LG 프로야구",
    max_reserve : 4,
    genre : "스포츠",

    reservationNo: "T2025071512345",
    seat_grade: "VIP석",
    seat_number: "L열 14",
    ticket_status: "pending",
    ticket_statusText: "인증필요",
    primaryButton: "얼굴 인증하기",
    primaryButtonAction: "verify",
    authDate: "",
  },
  {
    id: 4,
    artist: "류상진",
    date: "2025.09.10",
    ticket_date: "null",
    location: "올림픽공원",
    price: 88000,
    status: "예매중",
    image_url: "https://placehold.co/165x160",
    type: "new",
    name: "서울재즈페스티벌 2025",
    genre : "콘서트",

    reservationNo: "",
    seat_grade: "",
    seat_number: "",
    ticket_status: "null",
    ticket_statusText: "null",
    primaryButton: "null",
    primaryButtonAction: "null",
    authDate: "",
  },
  {
    id: 5,
    artist: "김재영",
    date: "2025.08.01",
    ticket_date: "2025.08.01 (금) 19:30",
    location: "롯데콘서트홀",
    price: 150000,
    status: "마감임박",
    image_url: "https://placehold.co/165x160",
    type: "null",
    name: "서울시향 정기공연",
    genre : "콘서트",

    reservationNo: "T2025071512345",
    seat_grade: "R석",
    seat_number: "A열 5",
    ticket_status: "pending",
    ticket_statusText: "인증필요",
    primaryButton: "얼굴 인증하기",
    primaryButtonAction: "verify",
    authDate: "",
  },
  {
    id: 6,
    artist: "김주하",
    date: "2025.07.30",
    ticket_date: "2025.07.30 (수) 10:00",
    location: "국립현대미술관",
    price: 100000,
    status: "마감임박",
    image_url: "https://placehold.co/165x160",
    type: "null",
    name: "현대미술전: 빛과 그림자",
    genre : "전시회",

    reservationNo: "T2025071512345",
    seat_grade: "일반",
    seat_number: "",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    isExpired: true,
    authDate: "2025.07.01 14:23",
  },
  {
    id: 7,
    artist: "차이코프스키",
    date: "2025.09.01",
    ticket_date: "2025.09.01 (월) 19:00",
    location: "세종문화회관",
    price: 200000,
    status: "예매중",
    image_url: "https://placehold.co/165x160",
    type: "null",
    name : "백조의 호수",
    genre : "공연",

    reservationNo: "T2025071512345",
    seat_grade: "S석",
    seat_number: "G열 8",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    authDate: "2025.07.01 14:23",
  },
  // ...필요한 만큼 추가
];
