// App/assets/events/EventsMock.tsx

// 좌석 데이터 zone, seat_number, name 분리 자동화 함수
function splitSeats(seats: any[], zone: any): any[] {
  return seats.map((seat: any) => {
    let zoneName = zone;
    let seatNum = seat.seat_number;
    let name = seat.seat_number;
    // seat_number가 'VIP-A1' 등 '-' 포함 시 분리
    if (seat.seat_number.includes("-")) {
      const parts = seat.seat_number.split("-");
      if (parts.length === 2) {
        zoneName = parts[0];
        seatNum = parts[1];
      } else if (parts.length > 2) {
        zoneName = parts.slice(0, -1).join("-");
        seatNum = parts[parts.length - 1];
      }
    }
    return {
      zone: zoneName,
      seat_number: seatNum,
      name,
      seat_status: seat.seat_status,
    };
  });
}

export const events = [
  //NULL값은 추후 수정 필요할수도?
  {
    id: 1,
    artist: "BTS",
    date: "2025.08.15",
    location: "서울 올림픽 주경기장",
    description:
      "🎤 아티스트: BTS\n📅 일시: 2025년 8월 15일 (금)\n📍 장소: 서울 올림픽 주경기장\n🕖 시간: 오후 7시 (예정)\n🚪 입장: 오후 5시 30분부터 시작\n🎫 티켓 오픈: 2025년 7월 20일 (토) 오후 8시, 위버스/인터파크 티켓 동시 오픈\n\n⸻\n\n🔔 유의사항\n• 본 공연은 전석 지정 좌석제로 운영됩니다.\n• 본인 확인을 위한 실물 신분증 필수 지참.\n• 리셀 및 불법 티켓 거래는 엄격히 금지됩니다.\n\n⸻\n\n💜 팬을 위한 안내\n• 굿즈 판매는 공연 당일 오후 1시부터 진행 예정입니다.\n• 입장 전 포토존 및 아미존 운영 예정",
    price: 165000,
    status: "인기",
    image_url:
      "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTEyMjdfMjE2%2FMDAxNjQwNTkwNTcxNTE1.Ugpe6qfQiknPtiPXII-aGpz5pHpZrtt8QAmAiGqzMBkg.PSkT39LpQADIpBF_Z_adgCO5TJNEOhS2EPW9ZdsgV90g.PNG.haeju10000%2F3444.png&type=sc960_832",
    type: "popular",
    name: "BTS 월드투어 2025",
    max_reserve: 4,
    genre: "콘서트",

    reservationNo: "T2025071512345",
    event_times: [
      {
        event_date: "2025-08-15",
        start_time: "19:00:00",
        end_time: "21:30:00",
        zones: [
          {
            rank: "VIP",
            price: 165000,
            total_count: 60,
            available_count: 40,
            seats: splitSeats(
              [
                { seat_number: "VIP-A1", seat_status: "available" },
                { seat_number: "VIP-A2", seat_status: "booked" },
                { seat_number: "VIP-A3", seat_status: "available" },
                { seat_number: "VIP-A4", seat_status: "available" },
                { seat_number: "VIP-A5", seat_status: "available" },
                { seat_number: "VIP-A6", seat_status: "available" },
                { seat_number: "VIP-A7", seat_status: "available" },
                { seat_number: "VIP-A8", seat_status: "available" },
                { seat_number: "VIP-A9", seat_status: "available" },
                { seat_number: "VIP-A10", seat_status: "available" },
                { seat_number: "VIP-A11", seat_status: "available" },
                { seat_number: "VIP-A12", seat_status: "available" },
                { seat_number: "VIP-A13", seat_status: "available" },
                { seat_number: "VIP-A14", seat_status: "available" },
                { seat_number: "VIP-A15", seat_status: "available" },
                { seat_number: "VIP-B1", seat_status: "available" },
                { seat_number: "VIP-B2", seat_status: "available" },
                { seat_number: "VIP-B3", seat_status: "available" },
                { seat_number: "VIP-B4", seat_status: "available" },
                { seat_number: "VIP-B5", seat_status: "available" },
                { seat_number: "VIP-B6", seat_status: "available" },
                { seat_number: "VIP-B7", seat_status: "available" },
                { seat_number: "VIP-B8", seat_status: "available" },
                { seat_number: "VIP-B9", seat_status: "available" },
                { seat_number: "VIP-B10", seat_status: "available" },
                { seat_number: "VIP-B11", seat_status: "available" },
                { seat_number: "VIP-B12", seat_status: "available" },
                { seat_number: "VIP-B13", seat_status: "available" },
                { seat_number: "VIP-B14", seat_status: "available" },
                { seat_number: "VIP-B15", seat_status: "available" },
                { seat_number: "VIP-C1", seat_status: "available" },
                { seat_number: "VIP-C2", seat_status: "available" },
                { seat_number: "VIP-C3", seat_status: "available" },
                { seat_number: "VIP-C4", seat_status: "available" },
                { seat_number: "VIP-C5", seat_status: "available" },
                { seat_number: "VIP-C6", seat_status: "available" },
                { seat_number: "VIP-C7", seat_status: "available" },
                { seat_number: "VIP-C8", seat_status: "available" },
                { seat_number: "VIP-C9", seat_status: "available" },
                { seat_number: "VIP-C10", seat_status: "available" },
                { seat_number: "VIP-C11", seat_status: "booked" },
                { seat_number: "VIP-C12", seat_status: "available" },
                { seat_number: "VIP-C13", seat_status: "available" },
                { seat_number: "VIP-C14", seat_status: "available" },
                { seat_number: "VIP-C15", seat_status: "available" },
                { seat_number: "VIP-D1", seat_status: "available" },
                { seat_number: "VIP-D2", seat_status: "available" },
                { seat_number: "VIP-D3", seat_status: "available" },
                { seat_number: "VIP-D4", seat_status: "available" },
                { seat_number: "VIP-D5", seat_status: "available" },
                { seat_number: "VIP-D6", seat_status: "available" },
                { seat_number: "VIP-D7", seat_status: "available" },
                { seat_number: "VIP-D8", seat_status: "available" },
                { seat_number: "VIP-D9", seat_status: "booked" },
                { seat_number: "VIP-D10", seat_status: "available" },
                { seat_number: "VIP-D11", seat_status: "available" },
                { seat_number: "VIP-D12", seat_status: "available" },
                { seat_number: "VIP-D13", seat_status: "available" },
                { seat_number: "VIP-D14", seat_status: "available" },
                { seat_number: "VIP-D15", seat_status: "available" },
              ],
              "VIP"
            ),
          },
          {
            rank: "R",
            price: 150000,
            total_count: 80,
            available_count: 60,
            seats: splitSeats(
              [
                { seat_number: "R-A1", seat_status: "available" },
                { seat_number: "R-A2", seat_status: "available" },
                { seat_number: "R-A3", seat_status: "available" },
                { seat_number: "R-A4", seat_status: "available" },
                { seat_number: "R-A5", seat_status: "available" },
                { seat_number: "R-A6", seat_status: "available" },
                { seat_number: "R-B1", seat_status: "available" },
                { seat_number: "R-B2", seat_status: "available" },
                { seat_number: "R-B3", seat_status: "available" },
                { seat_number: "R-B4", seat_status: "available" },
                { seat_number: "R-B5", seat_status: "available" },
                { seat_number: "R-B6", seat_status: "available" },
                { seat_number: "R-C1", seat_status: "available" },
                { seat_number: "R-C2", seat_status: "available" },
                { seat_number: "R-C3", seat_status: "available" },
                { seat_number: "R-C4", seat_status: "available" },
                { seat_number: "R-C5", seat_status: "available" },
                { seat_number: "R-C6", seat_status: "available" },
                { seat_number: "R-D1", seat_status: "available" },
                { seat_number: "R-D2", seat_status: "available" },
                { seat_number: "R-D3", seat_status: "available" },
                { seat_number: "R-D4", seat_status: "available" },
                { seat_number: "R-D5", seat_status: "available" },
                { seat_number: "R-D6", seat_status: "booked" },
                { seat_number: "R-E1", seat_status: "available" },
                { seat_number: "R-E2", seat_status: "available" },
                { seat_number: "R-E3", seat_status: "available" },
                { seat_number: "R-E4", seat_status: "available" },
                { seat_number: "R-E5", seat_status: "available" },
                { seat_number: "R-E6", seat_status: "available" },
              ],
              "R"
            ),
          },
          {
            rank: "S",
            price: 100000,
            total_count: 100,
            available_count: 80,
            seats: splitSeats(
              [
                { seat_number: "S-A1", seat_status: "available" },
                { seat_number: "S-A2", seat_status: "booked" },
                { seat_number: "S-A3", seat_status: "available" },
                { seat_number: "S-A4", seat_status: "available" },
                { seat_number: "S-A5", seat_status: "available" },
                { seat_number: "S-A6", seat_status: "booked" },
                { seat_number: "S-A7", seat_status: "booked" },
                { seat_number: "S-A8", seat_status: "available" },
                { seat_number: "S-B1", seat_status: "available" },
                { seat_number: "S-B2", seat_status: "available" },
                { seat_number: "S-B3", seat_status: "available" },
                { seat_number: "S-B4", seat_status: "available" },
                { seat_number: "S-B5", seat_status: "available" },
                { seat_number: "S-B6", seat_status: "available" },
                { seat_number: "S-B7", seat_status: "booked" },
                { seat_number: "S-B8", seat_status: "available" },
                { seat_number: "S-C1", seat_status: "available" },
                { seat_number: "S-C2", seat_status: "available" },
                { seat_number: "S-C3", seat_status: "available" },
                { seat_number: "S-C4", seat_status: "available" },
                { seat_number: "S-C5", seat_status: "available" },
                { seat_number: "S-C6", seat_status: "available" },
                { seat_number: "S-C7", seat_status: "available" },
                { seat_number: "S-C8", seat_status: "available" },
                { seat_number: "S-D1", seat_status: "available" },
                { seat_number: "S-D2", seat_status: "available" },
                { seat_number: "S-D3", seat_status: "available" },
                { seat_number: "S-D4", seat_status: "available" },
                { seat_number: "S-D5", seat_status: "available" },
                { seat_number: "S-D6", seat_status: "available" },
                { seat_number: "S-D7", seat_status: "available" },
                { seat_number: "S-D8", seat_status: "available" },
                { seat_number: "S-E1", seat_status: "available" },
                { seat_number: "S-E2", seat_status: "available" },
                { seat_number: "S-E3", seat_status: "available" },
                { seat_number: "S-E4", seat_status: "available" },
                { seat_number: "S-E5", seat_status: "booked" },
                { seat_number: "S-E6", seat_status: "available" },
                { seat_number: "S-E7", seat_status: "available" },
                { seat_number: "S-E8", seat_status: "available" },
              ],
              "S"
            ),
          },
          {
            rank: "A",
            price: 80000,
            total_count: 120,
            available_count: 100,
            seats: splitSeats(
              [
                { seat_number: "A-A1", seat_status: "available" },
                { seat_number: "A-A2", seat_status: "available" },
                { seat_number: "A-A3", seat_status: "available" },
                { seat_number: "A-A4", seat_status: "available" },
                { seat_number: "A-A5", seat_status: "available" },
                { seat_number: "A-A6", seat_status: "available" },
                { seat_number: "A-A7", seat_status: "booked" },
                { seat_number: "A-A8", seat_status: "booked" },
                { seat_number: "A-A9", seat_status: "available" },
                { seat_number: "A-A10", seat_status: "available" },
                { seat_number: "A-A11", seat_status: "available" },
                { seat_number: "A-A12", seat_status: "booked" },
                { seat_number: "A-A13", seat_status: "available" },
                { seat_number: "A-A14", seat_status: "available" },
                { seat_number: "A-A15", seat_status: "available" },
                { seat_number: "A-A16", seat_status: "available" },
                { seat_number: "A-B1", seat_status: "available" },
                { seat_number: "A-B2", seat_status: "available" },
                { seat_number: "A-B3", seat_status: "available" },
                { seat_number: "A-B4", seat_status: "available" },
                { seat_number: "A-B5", seat_status: "available" },
                { seat_number: "A-B6", seat_status: "available" },
                { seat_number: "A-B7", seat_status: "available" },
                { seat_number: "A-B8", seat_status: "available" },
                { seat_number: "A-B9", seat_status: "available" },
                { seat_number: "A-B10", seat_status: "booked" },
                { seat_number: "A-B11", seat_status: "available" },
                { seat_number: "A-B12", seat_status: "available" },
                { seat_number: "A-B13", seat_status: "available" },
                { seat_number: "A-B14", seat_status: "available" },
                { seat_number: "A-B15", seat_status: "available" },
                { seat_number: "A-B16", seat_status: "available" },
              ],
              "A"
            ),
          },
        ],
      },
      {
        event_date: "2025-08-16",
        start_time: "19:00:00",
        end_time: "21:30:00",
        zones: [
          {
            rank: "VIP",
            price: 200000,
            total_count: 60,
            available_count: 40,
            seats: [
              { seat_number: "VIP-A1", seat_status: "available" },
              { seat_number: "VIP-A2", seat_status: "booked" },
              { seat_number: "VIP-A3", seat_status: "available" },
              { seat_number: "VIP-A4", seat_status: "available" },
              { seat_number: "VIP-A5", seat_status: "available" },
              { seat_number: "VIP-A6", seat_status: "available" },
              { seat_number: "VIP-A7", seat_status: "booked" },
              { seat_number: "VIP-A8", seat_status: "available" },
              { seat_number: "VIP-A9", seat_status: "available" },
              { seat_number: "VIP-A10", seat_status: "available" },
              { seat_number: "VIP-A11", seat_status: "available" },
              { seat_number: "VIP-A12", seat_status: "available" },
              { seat_number: "VIP-A13", seat_status: "available" },
              { seat_number: "VIP-A14", seat_status: "available" },
              { seat_number: "VIP-A15", seat_status: "available" },
            ],
          },
          {
            rank: "R",
            price: 150000,
            total_count: 80,
            available_count: 60,
            seats: [
              { seat_number: "R-A1", seat_status: "booked" },
              { seat_number: "R-A2", seat_status: "available" },
              { seat_number: "R-A3", seat_status: "available" },
              { seat_number: "R-A4", seat_status: "available" },
              { seat_number: "R-A5", seat_status: "available" },
              { seat_number: "R-A6", seat_status: "available" },
              { seat_number: "R-B1", seat_status: "booked" },
              { seat_number: "R-B2", seat_status: "available" },
              { seat_number: "R-B3", seat_status: "available" },
              { seat_number: "R-B4", seat_status: "available" },
              { seat_number: "R-B5", seat_status: "available" },
              { seat_number: "R-B6", seat_status: "available" },
              { seat_number: "R-C1", seat_status: "booked" },
              { seat_number: "R-C2", seat_status: "available" },
              { seat_number: "R-C3", seat_status: "available" },
              { seat_number: "R-C4", seat_status: "available" },
              { seat_number: "R-C5", seat_status: "available" },
              { seat_number: "R-C6", seat_status: "available" },
              { seat_number: "R-D1", seat_status: "acailable" },
              { seat_number: "R-D2", seat_status: "available" },
              { seat_number: "R-D3", seat_status: "available" },
              { seat_number: "R-D4", seat_status: "available" },
              { seat_number: "R-D5", seat_status: "available" },
              { seat_number: "R-D6", seat_status: "available" },
              { seat_number: "R-E1", seat_status: "available" },
              { seat_number: "R-E2", seat_status: "available" },
              { seat_number: "R-E3", seat_status: "available" },
              { seat_number: "R-E4", seat_status: "booked" },
              { seat_number: "R-E5", seat_status: "available" },
              { seat_number: "R-E6", seat_status: "available" },
            ],
          },
          {
            rank: "S",
            price: 100000,
            total_count: 100,
            available_count: 80,
            seats: [
              { seat_number: "S-A1", seat_status: "available" },
              { seat_number: "S-A2", seat_status: "available" },
              { seat_number: "S-A3", seat_status: "available" },
              { seat_number: "S-A4", seat_status: "available" },
              { seat_number: "S-A5", seat_status: "available" },
              { seat_number: "S-A6", seat_status: "available" },
              { seat_number: "S-A7", seat_status: "available" },
              { seat_number: "S-A8", seat_status: "available" },
              { seat_number: "S-B1", seat_status: "available" },
              { seat_number: "S-B2", seat_status: "available" },
              { seat_number: "S-B3", seat_status: "available" },
              { seat_number: "S-B4", seat_status: "available" },
              { seat_number: "S-B5", seat_status: "available" },
              { seat_number: "S-B6", seat_status: "available" },
              { seat_number: "S-B7", seat_status: "available" },
              { seat_number: "S-B8", seat_status: "available" },
              { seat_number: "S-C1", seat_status: "available" },
              { seat_number: "S-C2", seat_status: "available" },
              { seat_number: "S-C3", seat_status: "available" },
              { seat_number: "S-C4", seat_status: "available" },
              { seat_number: "S-C5", seat_status: "available" },
              { seat_number: "S-C6", seat_status: "available" },
              { seat_number: "S-C7", seat_status: "available" },
              { seat_number: "S-C8", seat_status: "available" },
              { seat_number: "S-D1", seat_status: "available" },
              { seat_number: "S-D2", seat_status: "available" },
              { seat_number: "S-D3", seat_status: "available" },
              { seat_number: "S-D4", seat_status: "available" },
              { seat_number: "S-D5", seat_status: "available" },
              { seat_number: "S-D6", seat_status: "booked" },
              { seat_number: "S-D7", seat_status: "available" },
              { seat_number: "S-D8", seat_status: "available" },
              { seat_number: "S-E1", seat_status: "available" },
              { seat_number: "S-E2", seat_status: "available" },
              { seat_number: "S-E3", seat_status: "available" },
              { seat_number: "S-E4", seat_status: "available" },
              { seat_number: "S-E5", seat_status: "available" },
              { seat_number: "S-E6", seat_status: "available" },
              { seat_number: "S-E7", seat_status: "available" },
              { seat_number: "S-E8", seat_status: "available" },
            ],
          },
          {
            rank: "A",
            price: 80000,
            total_count: 120,
            available_count: 100,
            seats: [
              { seat_number: "A-A1", seat_status: "available" },
              { seat_number: "A-A2", seat_status: "available" },
              { seat_number: "A-A3", seat_status: "available" },
              { seat_number: "A-A4", seat_status: "available" },
              { seat_number: "A-A5", seat_status: "available" },
              { seat_number: "A-A6", seat_status: "available" },
              { seat_number: "A-A7", seat_status: "available" },
              { seat_number: "A-A8", seat_status: "available" },
              { seat_number: "A-A9", seat_status: "available" },
              { seat_number: "A-A10", seat_status: "available" },
              { seat_number: "A-A11", seat_status: "available" },
              { seat_number: "A-A12", seat_status: "available" },
              { seat_number: "A-A13", seat_status: "available" },
              { seat_number: "A-A14", seat_status: "available" },
              { seat_number: "A-A15", seat_status: "available" },
              { seat_number: "A-A16", seat_status: "available" },
              { seat_number: "A-B1", seat_status: "available" },
              { seat_number: "A-B2", seat_status: "available" },
              { seat_number: "A-B3", seat_status: "available" },
              { seat_number: "A-B4", seat_status: "available" },
              { seat_number: "A-B5", seat_status: "available" },
              { seat_number: "A-B6", seat_status: "available" },
              { seat_number: "A-B7", seat_status: "available" },
              { seat_number: "A-B8", seat_status: "available" },
              { seat_number: "A-B9", seat_status: "available" },
              { seat_number: "A-B10", seat_status: "available" },
              { seat_number: "A-B11", seat_status: "available" },
              { seat_number: "A-B12", seat_status: "available" },
              { seat_number: "A-B13", seat_status: "available" },
              { seat_number: "A-B14", seat_status: "available" },
              { seat_number: "A-B15", seat_status: "available" },
              { seat_number: "A-B16", seat_status: "available" },
            ],
          },
        ],
      },
    ],
    seat_grade: "VIP석",
    seat_number: "L열 14",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    authDate: "2025.07.01 14:23",
  },
  {
    id: 2,
    artist: "심바, 닐라",
    date: "2025.07.20",
    location: "예술의전당",
    description:
      "📍 예술의전당\n📅 2025년 7월 20일 (일)\n🕕 공연 시간: 오후 6시 (예정)\n🚪 입장 시작: 오후 5시\n👥 1인 최대 예매 가능 수: 6매\n\n⸻\n\n🔔 유의사항\n• 본 공연은 지정 좌석제입니다.\n• 현장 수령 시 실물 신분증을 꼭 지참해주세요.\n• 티켓 취소 및 환불은 공연 3일 전까지 가능합니다.\n• 공연 중 사진 및 영상 촬영은 금지되어 있습니다.\n\n⸻\n\n🦁 관람 안내\n• 공연 시간은 약 150분 (인터미션 포함)입니다.\n• 8세 이상 관람가 (미취학 아동 입장 불가)\n• 공연 시작 후 입장은 제한될 수 있으니 여유 있게 도착해주세요.\n• 굿즈 판매는 공연 당일 오후 3시부터 예술의전당 로비에서 진행됩니다.",
    price: 120000,
    status: "마감임박",
    image_url:
      "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxOTA3MThfMjMz%2FMDAxNTYzNDE2NTUxNjI0.b642ZPcHx_Y1B5VFT1wYF-ElprSWnuwCICvkn8cdJWAg.IvoYNQ3ZSHjVVrKdfHggSrIyD_0ADp9SDHd4cVQW7G4g.JPEG.sunny9952%2F20190718_112058.jpg&type=sc960_832",
    type: "popular",
    name: "라이언 킹",
    max_reserve: 6,
    genre: "뮤지컬",

    reservationNo: "",
    event_times: [
      {
        event_date: "2025-07-20",
        start_time: "18:00:00",
        end_time: "20:30:00",
      },
    ],
    seat_grade: "",
    seat_number: "",
    ticket_status: "null",
    ticket_statusText: "null",
    primaryButton: "null",
    primaryButtonAction: "null",
    authDate: "",
  },
  {
    id: 3,
    artist: "두산, LG",
    date: "2025.07.25",
    location: "잠실야구장",
    description:
      "⚾ 두산 VS LG 프로야구\n📍 잠실야구장\n📅 2025년 7월 25일 (금)\n🕖 경기 시간: 오후 7시 (예정)\n🚪 입장 시작: 오후 5시 30분\n👥 1인 최대 예매 가능 수: 4매\n\n⸻\n\n🔔 유의사항\n• 본 경기는 지정 좌석제로 운영됩니다.\n• 티켓 수령 시 신분증 확인이 필요할 수 있습니다.\n• 우천 시 일정 변경 또는 취소될 수 있으며, 변경 시 별도 공지됩니다.\n• 티켓 환불은 경기 시작 3시간 전까지 가능합니다.\n\n⸻\n\n📣 관람 안내\n• 야구장 내 외부 음식 반입 제한 구역이 있을 수 있으니 사전 확인 바랍니다.\n• 응원용품(응원봉, 타올 등) 사용은 가능하나 타인 관람에 방해되지 않도록 주의해주세요.\n• 경기 시작 이후 입장 시 본인 좌석 외 지정된 구역에서 대기할 수 있습니다.\n• 현장에서는 구단 공식 굿즈 판매 부스도 운영됩니다.",
    price: 18000,
    status: "예매중",
    image_url:
      "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyNDA3MjBfMjE1%2FMDAxNzIxNDQzODkyNDgy.cK7QCQwtRN6zwONkq2o5y1zR2MLXsWIWM-NKF_eTpGwg.ByAnZ6kKHD989_BacimcOtBB5huMWKwGoFYglpJIWC0g.PNG%2Fimage.png&type=sc960_832",
    type: "new",
    name: "두산 VS LG 프로야구",
    max_reserve: 4,
    genre: "스포츠",

    reservationNo: "T2025071512345",
    event_times: [
      {
        event_date: "2025-07-25",
        start_time: "19:00:00",
        end_time: "21:30:00",
      },
    ],
    seat_grade: "VIP석",
    seat_number: "L열 14",
    ticket_status: "pending",
    ticket_statusText: "인증필요",
    primaryButton: "얼굴 인증하기",
    primaryButtonAction: "verify",
    authDate: "",
  },
  {
    id: 4,
    artist: "류상진",
    date: "2025.09.10",
    location: "올림픽공원",
    description:
      "🎷 서울재즈페스티벌 2025\n📍 올림픽공원\n📅 2025년 9월 10일 (수)\n🕒 공연 시간: 오후 3시 시작 (예정)\n🚪 입장 시작: 오후 1시부터\n🎟 티켓 가격: 88,000원\n👥 1인 최대 예매 가능 수: 별도 공지\n\n⸻\n\n🔔 유의사항\n• 본 공연은 야외 스탠딩 및 지정 좌석 구역으로 나뉘어 운영됩니다.\n• 티켓은 현장 수령 또는 모바일 티켓으로 제공됩니다.\n• 우천 시에도 공연은 예정대로 진행되며, 우비 착용을 권장드립니다.\n• 티켓 환불은 공연 3일 전까지 가능, 이후 환불 불가입니다.\n\n⸻\n\n🎶 관람 안내\n• 입장 시 보안 검사가 있을 수 있으니 가벼운 복장으로 방문해주세요.\n• 도시락 및 물병 반입 가능, 주류 및 유리병은 반입 금지입니다.\n• 공연장 내 푸드트럭, 굿즈존, 포토존 운영 예정",
    price: 88000,
    status: "예매중",
    image_url:
      "https://search.pstatic.net/common/?src=http%3A%2F%2Fimgnews.naver.net%2Fimage%2F009%2F2025%2F04%2F16%2F0005477351_002_20250416144107993.jpg&type=sc960_832",
    type: "new",
    name: "서울재즈페스티벌 2025",
    genre: "콘서트",

    reservationNo: "",
    event_times: [
      {
        event_date: "2025-09-10",
        start_time: "15:00:00",
        end_time: "19:30:00",
      },
    ],
    seat_grade: "VIP석 ",
    seat_number: "A열 1",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    authDate: "2025.07.01 14:23",
  },
  {
    id: 5,
    artist: "김재영",
    date: "2025.08.01",
    location: "롯데콘서트홀",
    price: 150000,
    status: "마감임박",
    image_url:
      "https://www.seoulphil.or.kr/file/displayFile?&fileNo=13333&downType=img",
    type: "null",
    name: "서울시향 정기공연",
    genre: "콘서트",

    reservationNo: "T2025071512345",
    event_times: [
      {
        event_date: "2025-08-01",
        start_time: "19:30:00",
        end_time: "21:30:00",
      },
    ],
    seat_grade: "R석",
    seat_number: "A열 5",
    ticket_status: "pending",
    ticket_statusText: "인증필요",
    primaryButton: "얼굴 인증하기",
    primaryButtonAction: "verify",
    authDate: "",
  },
  {
    id: 6,
    artist: "김주하",
    date: "2025.07.30",
    location: "국립현대미술관",
    price: 100000,
    status: "마감임박",
    image_url: "https://www.artbank.go.kr/data/art/pic/121/10364-02.jpg",
    type: "null",
    name: "현대미술전: 빛과 그림자",
    genre: "전시회",

    reservationNo: "T2025071512345",
    event_times: [],
    seat_grade: "일반",
    seat_number: "",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    isExpired: true,
    authDate: "2025.07.01 14:23",
  },
  {
    id: 7,
    artist: "차이코프스키",
    date: "2025.09.01",
    location: "세종문화회관",
    price: 200000,
    status: "예매중",
    image_url:
      "http://www.universalballet.com/kr/data/file/perf/thumb-2948667285_dQZ4BDwT_58c44a8a3b8022cab964f34d0bd6beda5374457f_300x428.jpg",
    type: "null",
    name: "백조의 호수",
    genre: "공연",

    reservationNo: "T2025071512345",
    event_times: [
      {
        event_date: "2025-09-01",
        start_time: "19:00:00",
        end_time: "21:30:00",
      },
    ],
    seat_grade: "S석",
    seat_number: "G열 8",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    authDate: "2025.07.01 14:23",
  },
  {
    id: 8,
    artist: "아무개",
    date: "2025.07.11",
    location: "세종문화회관",
    price: 100000,
    status: "마감",
    image_url:
      "https://www.sejongpac.or.kr/cmmn/file/imageSrc.do?fileStreCours=faec0c25744c22e99776405c0fa72802bd78877fc490743cb3553e70673cad94&streFileNm=75af6579693b02b45b842302dbb38ee62657b980fbf690d891fc361941a10452",
    type: "null",
    name: "뮤지컬 <팬텀> 10주년 기념 공연",
    genre: "공연",

    reservationNo: "T2025071112345",
    event_times: [
      {
        event_date: "2025-07-11",
        start_time: "14:30:00",
        end_time: "17:20:00",
      },
    ],
    seat_grade: "VIP석",
    seat_number: "A열 1",
    ticket_status: "verified",
    ticket_statusText: "인증완료",
    primaryButton: "QR코드 보기",
    primaryButtonAction: "qr",
    isExpired: true,
    authDate: "2025.07.01 14:23",
  },
  // ...필요한 만큼 추가
];
