name: π§­ Chore
description: κ°λ° μ„Έν…
labels: ["π§­ Chore"]
body:
  - type: markdown
    attributes:
      value: |
        ## β¨ μ„Έν…ν•  ν™κ²½  
        <br>

        ### π“• λ νΌλ°μ¤  
        <br>
